name: hello-world

on: push

jobs:
  Hello-world-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: check out repos code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
